export class QuestionsData {
  public static INVESTOR_QUESTIONS = [
    "What do you understand that others don't?",
    "Why will you succeed?",
    "How big is the opportunity?",
    "What hurdles are you anticipating?",
    "Who would use your product?",
    "How much does it cost to acquire customers?",
    "How will you make money?",
    "How much money could you make per year?",
    "How many users do you have?",

    "How are you meeting customers?",
    "How are you understanding customer needs?",
    "How will you get users?",

    "So what are you working on?",

    "How does your product work?",
    "How is your product different?",
    "What are you going to do next?",
    "What's new about what you make?",
    "What makes you different from existing options?",
    "Who needs what you're making?",
    "How do you know customers need what you're making?",
    "Why isn't someone already doing this?",
    "What obstacles will you face and how will you overcome them?",
    "How will customers and/or users find out about you?",
    "What resistance will customers have to trying you and how will you overcome it?",
    "What are the key things about your field that outsiders don't understand?",

    "Who is going to be your first paying customer?",
    "If your startup succeeds, what additional areas might you be able to expand into?",

    "What have you learned so far from working on your product?",
    "Six months from now, what's going to be your biggest problem?",
    "Where do new users come from?",
    "What is your growth like?",
    "What's the conversion rate?",
    "What makes new users try you?",
    "Why do the reluctant users hold back?",
    "What are the top things users want?",
    "What has surprised you about user behaviour?",
    "What's an impressive thing you have done?",
    "What do you understand about your users?",
    "Why did you pick this idea to work on?",
    "What domain expertise do you have?",
    "Who are your competitors?",
    "Who might become competitors?",
    "What competition do you fear most?",
    "What is your distribution strategy?",
    "What will you do if we don't fund you?",
    "Are you open to changing your idea? ",
    "Tell us about a tough problem you solved?",
    "In what ways are you resourceful?",
    "What's the worst thing that has happened?",
    "What's the biggest mistake you have made?",
    "What is your burn rate?",
    "How long can you go before funding?",
    "What is the next step with the product evolution?",
    "Who would be your next hire?",
    "How do you know people want this?",
    "What will prevent others from becoming fast followers?",
    "What barriers to entry are there for your business?",
    "How long does customer acquisition take?",
    "What is your customer retention strategy?",
    "What is your key personnel risk?",
    "What are the key drivers of business performance?",
    "What change will you make to improve your business performance?",
    "Why am I the right investor for your business?",
  ];

  public static INVESTOR_TIPS = [
    "Try to answer using new language each time you answer the question.",
    "Try to have quick and concise answers.",
    "Try to answer in 2 to 3 sentences.",
    "Answer like you would in a conversation, this is not a presentation.",
    "When talking to a potential investor, be substantive, and get straight to the point.",
  ];

  public static CUSTOMER_QUESTIONS = [
    "How does your product work in more detail?",
    "How is your product different?",
    "What's new about what you make?",
    "What makes you different from existing options?",
    "What are the benefits that users are most excited about?",
    "Have you attracted other customers in my industry?",
    "How is your product reliable?",
    "How do you keep my data secure?",
    "Does your product integrate with other systems that customers use?",
    "Does the product require user training?",
    "How is pricing structured?",
    "Who is your main competitor and why shouldn't I go with their offer?",
    "What have you learned from POCs?",
    "What obstacles do you face?",
    "Are there any challenges for customers to switch to your product?",
    "What are the response times for customer issues or bug fixes?",
    "What new features will you build next?",
    "How soon can we sign up?",
    "Why should I buy your product/service?",
    "Why do I need your product?",
    "What changes to my current systems are required?",
    "I need to simplify my business. What processes will your product replace?",
    "Why did you choose this specific technology?",
    "What is the problem you are trying to solve?",
    "Which of my current priorities do you think your product addresses?",
    "Why do you think your product will work for a customer like me?",
    "What does it cost me in internal time/resources to bring your product onstream?",
    "Why do I need your product?",
    "What training/onboarding is required for my team before they can use your product?",
  ];

  public static CUSTOMER_TIPS = [
    "Try to answer using new language each time you answer the question.",
    "Try to have quick and concise answers.",
    "Try to answer in 2 to 3 sentences.",
    "Answer like you would in a conversation, this is not a presentation.",
  ];
  
  public static LIVE_QUESTIONS = [
    "What's something the audience doesn't know about your startup?",
  ];
  
  public static LIVE_TIPS = [
    "Try to answer using new language each time you answer the question.",
    "Try to have quick and concise answers.",
    "Try to answer in 2 to 3 sentences.",
    "Answer like you would in a conversation, this is not a presentation.",
  ];
    
}
