// Questions
var q = [
  'Why did you choose this specific technology?',
  'Is this product compliant with sharia law?',
  'What is the problem you are trying to resolve?',
  'We have just spent hundreds of millions rebuilding our global P2P /O2C systems and processes, why should we go through another change now?',
  'I need to simplify my business, what systems will this product replace?',
  'Which of my current priorities do you think this product addresses?',
  'How is Argand different to Supply Chain Financing?',
  'What happens with the invoice – if there is a dispute how will it be resolved following immediate payment?',
  'Will this product cover all our global sales?',
  'Traditionally digital transformation and process change is very expensive and involves lots of people – can you do this differently?',
  'Why do you think this product will work for a distributor like us?',
  'A lot of our business involves providing manpower for customers – can Argand deal with that?',
  'Why should I pay my suppliers instantaneously?',
  'How does this product help buyers get away from the old way of working of putting pressure on suppliers?',
  'What changes to my current SoR are required to accommodate Argand APIs and new business processes?',
  'What barriers to entry are there for your business?',
  'When will I get my money back?',
  'How long does customer acquisition take?',
  'What is your customer retention strategy?',
  'What is your key personnel risk?',
  'What are the key drivers of business performance?',
  'What change will you make to improve your business performance?',
  'Why am I the right investor for your business?',
  'What does it cost me in internal time/resources to bring your product onstream?',
  'Why do I need your product?',
  'How much/what sort training/onboarding do I need do give my team before they can use your product?',
  'Do you offer a trial period?',
  'What is your pricing model?',
];

// Tips
var tips = [
  'Try to answer using new language each time you answer the question.',
  'Try to have quick and concise answers.',
  'Try to answer in 2 to 3 sentences.',
  'Avoid buzzwords and extremely specific jargon.',
  'Answer like you would in a conversation, this is not a presentation.',
  'When talking to a potential investor, be substantive, and get straight to the point.',
];
