// Questions
var q = [
	'So what are you working on?',
	'Why did you pick this idea to work on?',
	'What domain expertise do you have?',
	'What do you understand that others don&#39;t?',
	'Why will you succeed?',
	'How big an opportunity is there?',
	'What hurdles are you anticipating?',
	'Who would use your product?',
	'What is the cost to acquire customers (CAC)?',
	'How will you make money?',
	'How much money could you make per year?',
	'How many users do you have?', 
	'How are you meeting customers?',
	'How are you understanding customer needs?',
	'How will you get users?',
	'Who will your next hire be?',
	'How does your product work?',
	'How is your product different?',
	'What are you going to do next?',
	'What&#39;s new about what you make?',
	'What makes you different from existing options?',
	'Who needs what you&#39;re making?',
	'How do you know customers need what you&#39;re making?',
	'Why isn&#39;t someone already doing this?',
	'What obstacles will you face and how will you overcome them?',
	'How will customers find out about you?',
	'What resistance will customers have to trying you and how will you overcome it?',
	'What are the key things about your field that outsiders don&#39;t understand?',
	'Who is going to be your first paying customer?',
	'If your startup succeeds, what additional areas will you be able to expand into?',
	'What have you learned so far from working on your product?',
	'Six months from now, what&#39;s going to be your biggest problem?',
	'Where do new users come from?',
	'What is your growth like?',
	'What&#39;s the conversion rate?',
	'What makes new users try you?',
	'Why do the reluctant users hold back?',
	'What are the top things users want?',
	'What has surprised you about user behaviour?',
	'What&#39;s an impressive thing you have done?',
	'What do you understand about your users?',
	'Who are your competitors?',
	'Who might become your competitors?',
	'What competition do you fear most?',
	'What is your distribution strategy?',
	'What will you do if we don&#39;t fund you?',
	'Are you open to changing your idea? ',
	'Tell us about a tough problem you solved?',
	'In what ways are you resourceful?',
	'What&#39;s the worst thing that has happened?',
	'What&#39;s the biggest mistake you have made?',
	'What&#39;s your burn rate?',
	'How long can you go before funding?',
	'What&#39;s the next step with your product evolution?',
	'How do you know people want this?',
	'What will prevent others from becoming fast followers?',
	'What are the barriers to entry?',
	'How long does it take to acquire customers?',
	'What&#39;s your customer retention strategy?',
	'What&#39;s your key personnel risk?',
	'What are the key drivers of business performance?',
	'What change will you make to improve your business performance?',
	'Why am I the right investor for you?',
	'At what scale do you need to acquire customers to become profitable?'

];

// Tips
var tips = [
	'Try to answer using new language each time you answer the question.',
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to a potential investor, be substantive, and get straight to the point.',

];
